project:
  type: book

book:
  title: Introduction to Formal Mathematics with Lean 4
  author: Xingyu Zhong
  date: 2025/12/05
  chapters:
    - index.qmd
    - part: Prelude
      chapters:
        - intro.qmd
        - 01-intro.qmd
    - part: Prop
      chapters:
        - 02-logic.qmd
        - 03-logic.qmd
        - 04-logic.qmd
    - part: Type
      chapters:
        - 05-type.qmd
        - 06-ineq.qmd
        - 07-analysis.qmd
    - part: Structure
      chapters:
        - 08-group.qmd
        - 09-subgroup.qmd
        - 10-quotient.qmd
  appendices:
    - poster.qmd

# bibliography: examples/bibliography.bib

shift-heading-level-by: 0 # Seemingly Quarto will -1 automatically for books. So leave this at 0.

format:
  pdf:
    documentclass: book
    custom-theorem:
      numbered-within: chapter
      numbered-alike: true
